# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

dotenv: ['project.ini']

silent: true

includes:
  _cleanup: https://raw.githubusercontent.com/sig9org/tasks/main/tasks/_cleanup.yml
  _docker_buildx: https://raw.githubusercontent.com/sig9org/tasks/main/tasks/_docker_buildx.yml
  _skopeo: https://raw.githubusercontent.com/sig9org/tasks/main/tasks/_skopeo.yml
  _time: https://raw.githubusercontent.com/sig9org/tasks/main/tasks/_time.yml

tasks:
  default:
    cmds:
      - task --list

  cleanup:
    aliases: [c]
    desc: "Cleanup unnecessary files"
    cmds:
      - defer:
          task: _time:end
          vars:
            START_TIME: '{{.START_TIME}}'
      - task: _cleanup:start

  docker-build-version:
    aliases: [db]
    desc: "Build and export to the registry"
    cmds:
      - defer:
          task: _time:end
          vars:
            START_TIME: '{{.START_TIME}}'
      - task: _docker_buildx:version

  docker-tags:
    aliases: [dt]
    desc: "List the tags registered on Docker Hub"
    cmds:
      - defer:
          task: _time:end
          vars:
            START_TIME: '{{.START_TIME}}'
      - task: _skopeo:tags
