# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  NAME: "zensical"
  VERSION: "0.0.43"

tasks:
  default:
    cmds:
      - task --list

  build:
    aliases: [b]
    desc: Build and export to the registry
    cmds:
      - time docker buildx build --platform linux/amd64,linux/arm64 --output=type=registry --tag sig9/{{.NAME}}:latest --tag sig9/{{.NAME}}:{{.VERSION}} versions/{{.VERSION}}/

  tags:
    desc: List the tags registered on Docker Hub
    cmds:
      - skopeo list-tags docker://docker.io/sig9/{{.NAME}} | jq -r '.Tags[]' | sort -V
